name: "Модуль 4, Задача 1: Стильная кнопка"

env:
  FOLDER_WITH_TASK: "Module 4/1. styled-button"

on:
  push:
    paths:
      - "Module 4/1. styled-button/**"

jobs:
  test:
    name: Запускаем тесты
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm install
      - name: Run tests
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm test
