name: "Модуль 5, Задача 2: Products CRUB"

env:
  FOLDER_WITH_TASK: "Module 5/2. products-crud"

on:
  push:
    paths:
      - "Module 5/2. products-crud/**"

jobs:
  test:
    name: Запускаем тесты
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm install
      - name: Run tests
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm test
